config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get '/signup', to: "users#new"
  get "/home", to: "static_pages#home"
  get '/help', to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts, only: [:edit, :update, :create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :link, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "ブックマークが登録されました！"
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render "static_pages/home"
    end
  end
  
  def destroy
    @post.destroy
    flash[:success] = "ブックマークを削除しました"
    redirect_to request.referrer || root_url
  end
  
  def edit
    @feed_items = current_user.feed.paginate(page: params[:page])
  end
  
  def update
    if @post.update_attributes(post_params)
      flash[:success] = "ブックマークを更新しました"
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render "edit"
    end
  end
  
  private 
    
    def post_params
      params.require(:post).permit(:chapter, :title, :link, :memo)
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">

  <span class="under">チュートリアルのチャプター</span>
  <span class="content"><%= simple_format(post.chapter) %></span>
  
  <span class="under">タイトル</span>
  <span class="content"><%= link_to simple_format(post.title), post.link, target: :_blank %></span>
  
  <span class="under">概要</span>
  <span class="content"><%= simple_format(post.memo) %></span>
  
  <% if current_user?(post.user) %>
    <%= link_to "ブックマークを編集", edit_post_path(post) %> | 
    <%= link_to "ブックマークを削除", post_path(post), method: :delete,
                                 data: { confirm: "本当に削除してよろしいですか？" }%>
  <% end %>
</li>

app/views/posts/edit.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render "shared/user_info" %>
    </section>
    <section class="post_form">
      <!--もともと入力されていたものを表示する-->
      <%= form_for(@post) do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="field">
          <%= f.label :chapter, "チュートリアルのチャプター" %>
          <%= f.text_field :chapter, autocomplete: "off", class: "form-color" %>
          
          <%= f.label :title, "タイトル" %>
          <%= f.text_field :title, autocomplete: "off", class: "form-color" %>
          
          <%= f.label :link, "リンク" %>
          <%= f.text_area :link, autocomplete: "off", class: "form-color" %>
          
          <%= f.label :memo, "概要" %>
          <%= f.text_area :memo, autocomplete: "off", class: "form-color" %>
        </div>
        <%= f.submit "ブックマークを更新！", class: "btn btn-primary" %>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>ブックマーク一覧</h3>
    <%= render "shared/feed" %>
  </div>
</div>